### ISSUE TITLE
420 - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by Turretrooper** [NFLD99/Better-Discord#10]
It doesn't look like what it's supposed to look like.

**Comment by TheStrato** [comment]
Can you please just join our discord support server for this, it will be a lot easier to troubleshoot your theme on there. https://nfld99.com/discord

**Comment by NFLD99** [comment]
Workings as intended. Please read what the file says.

**Comment by NFLD99** [comment]
Closed, working as intended.
