### ISSUE TITLE
ReZero - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by Brandon8901** [NFLD99/Better-Discord#13]
Hello! Today I was enjoying the beauty of Rem and Ram and I deactivated it to move some things and I did not leave the bottom I left to download again I tried it like 4 times and nothing and I still hope it works I can not live without them. :,v

**Comment by TwinDragon** [comment]
If you're having the issue of black text and things not looking quite right, you have tried to download it again from the site, correct? Some things did get changed in an update a couple days ago and all themes need to be redownloaded.

**Comment by Brandon8901** [comment]
If I downloaded it from the right place, I only deactivated the issue 1 or 2 hours ago because I was trying another Re: zero and decided to activate the theme again but I only get a text that I designed to direct me to a link that text is over a blue and pink background and I try to see if I can solve it but I can not. xd

**Comment by TwinDragon** [comment]
Ah. Download the themes from https://www.nfld99.com, anything from Discord Source is not supported and will be working as intended if gotten from there. I can't help you any further than this.

**Comment by Brandon8901** [comment]
Oh thank you very much sorry for the inconvenience and if I have bad spelling is that I do not know much English but I will try to settle for another who sees Re: zero. xdd
