### ISSUE TITLE
Meta not found with Dark Wood Theme

### ISSUE THREAD

**Issue by Pantherax** [NFLD99/Better-Discord#2]
Been trying to solve the META not found issues with the Dark Wood Theme, all remedies I've been trying are just failing.
![actual problemo](https://user-images.githubusercontent.com/39955814/40978047-9a1d92d6-68a0-11e8-8f83-abbe5d785a6c.PNG)

**Comment by TheStrato** [comment]
They are away for the week so it might take them a bit to respond to this but they have gotten this message.

**Comment by NFLD99** [comment]
Try re-downloading the theme from my website, if you get the same error please send a screenshot of the file when it's opened, also see if it happens with any of my main themes, I don't have access to my PC for the week so bug testing is not possible from my end ATM
