### ISSUE TITLE
Mashed users and chat area.

### ISSUE THREAD

**Issue by oguzdeler** [NFLD99/Better-Discord#2]
Users are above chat. [like this](https://imgur.com/AgSXbiz)

I have "NFLDInc_Plugin.plugin" installed and activated. Tried two different discord versions and different OS's.

**Comment by NFLD99** [comment]
i will lookinto this when i get home, can you please provide some information for me?
Plugins active:

Themes active:

Extra css active:

Discord client abd version {found in settings at the bottom}

Theme version[found in the title bar]:

**Comment by oguzdeler** [comment]
![resim](https://user-images.githubusercontent.com/69536507/120940263-0bc35480-c725-11eb-8f6a-3f54e4d86a68.png)
All this plugins are active. Issue still exists without them.
Themes are 
![resim](https://user-images.githubusercontent.com/69536507/120940348-80968e80-c725-11eb-8aee-6fbf67d7afe7.png)
Avatars by you
Popout_Text_and_voice by you
Fallout 4 terminal by bates.
Blackhole by Horta
(I changed themes deactiaved all the others and tried, same issue)

I don't have extra css

Discord version etc.
![resim](https://user-images.githubusercontent.com/69536507/120940366-9d32c680-c725-11eb-9cef-3c1d2d1d4360.png)
I probably have different version on linux but they both have same issue.

Avatars v4
Fallout v1.0
Popout_Text_And_Voiceversion auto updates(doesn't have any numeric value as version)
Blackhole(I don't know I just used small part of the css)

**Comment by NFLD99** [comment]
Dose it persist if you use one of our themes? It may be an issue with the theme you are using

**Comment by NFLD99** [comment]
If it doesn't persist can you link the theme you are using I will see if I can't override it

**Comment by oguzdeler** [comment]
You're right. The other themes and default discord persist on issue. NFLD99 themes working perfectly fine. Here is the [terminal theme](https://betterdiscord.app/theme/Fallout%204%20Terminal)

**Comment by oguzdeler** [comment]
If you look it that way it's not a bug, other themes are overriting Popout mini theme. For now other themes are not supported.

**Comment by NFLD99** [comment]
When I get home I'll update the mini theme, you are using a fresh version of it correct?

**Comment by oguzdeler** [comment]
Yes I am using newest version.
Discovered something, I think it only works on main and transparent themes. Just for that I tried one theme from every group.

**Comment by NFLD99** [comment]
If thats the case that's really odd as they all use the same backend, thank you for the bug reports thought and I will look into it tonight!
