### ISSUE TITLE
Resource Update Theme Scratched_Up_v2

### ISSUE THREAD

**Issue by 73CH9ICH13F** [NFLD99/Better-Discord#3]
Hello the Theme Scratched_Up_v2 is using too much resources and when you're not using even Discord it still using a lot of Resources. Maybe make update with less resource usage.
Thanks

**Comment by NFLD99** [comment]
Disable animations if you have them on in the theme file, nfld99.com/wiki

**Comment by NFLD99** [comment]
This has been closed due to inactivity.
