### ISSUE TITLE
Rainbow Six Siege Outbreak - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by matimontooo** [NFLD99/Better-Discord#37]
NO FUNCIONA!!!

**Comment by TheStrato** [comment]
Trabajando según lo previsto. Descargó un archivo incorrecto. No utilice BetterDocs / DiscordSource. Vuelva a descargarlo desde: https://nfld99.com. El sitio desde el que descargó este tema no tiene permiso para alojar mis archivos ni enlazar a mis repositorios. para eliminar mis temas varias veces. Si necesita soporte, únase al servidor de soporte: https://nfld99.com/discord ~ NFLD99
