### ISSUE TITLE
Move copyright and license to a LICENSE file

### ISSUE THREAD

**Issue by locness3** [NFLD99/Better-Discord#43]

**Comment by NFLD99** [comment]
May I ask what the point of this would be?

**Comment by locness3** [comment]
It shouldn't be in the readme

**Comment by TwinDragon** [comment]
And why shouldn't it be? It doesn't matter so long as it's visible in one form another.

**Comment by locness3** [comment]
It's just more common for it to be in a separate file

**Comment by TwinDragon** [comment]
Just because it's more common to see doesn't really make it a rule or a requirement to be in it's own file. Each repo owner is free to do how they wish to publish their license and copyright notices.
