### ISSUE TITLE
Timestamp Var Does Not Change Color

### ISSUE THREAD

**Issue by TwinDragon** [NFLD99/Better-Discord#47]
Looks like Discord changed the class name of the Timestamp. I dug around to find the new one: `.timestamp-3ZCmNB` - I'd make a PR maybe, but I don't have a way to test it locally right now like you do, so that should help.

**Comment by The-Shiz** [comment]
This still opened?

**Comment by TwinDragon** [comment]
Commit a2eabafc346595837fecf5db9a8e27e40ee29b5e fixed this, so I'll just close it now. lol
