### ISSUE TITLE
Domain down?

### ISSUE THREAD

**Issue by SaengerItsWar** [NFLD99/Better-Discord#48]
is it possible that your domain is expired?

**Comment by TheStrato** [comment]
We are working on this and moving things around and updating. Some things came up and we are updating it. We will post information in the discord as it becomes available.

**Comment by The-Shiz** [comment]
Hey I just got home from hospital, I was booted or something all servers for me are gone.

**Comment by TheStrato** [comment]
NFLD left. Devil took over. You're still on the main guild. I will ping you in Staff chat.
