### ISSUE TITLE
Rainbow Six Siege Outbreak - BetterDocs - [Issue Report]

### ISSUE THREAD

**Issue by Pyxel091** [NFLD99/Better-Discord#9]
I can't manage roles when I use this theme. Which bothers me a lot since I really like this theme.

**Comment by NFLD99** [comment]
I do not support betterdocs my themes are there without permission, if you want my themes use the OFFICAL BD servers and use my website https://nfld99.com

**Comment by NFLD99** [comment]
Closed Due To Non Supported Site.
